### ISSUE TITLE
Crediting/modifying

### ISSUE THREAD

**Issue by SyedOmarNooredu** [jgardner8/engine-sound-simulator#1]
Hello
I have made an indirect fork of your repository at [https://github.com/SyedOmarNooredu/Engine-sound-simulator---](https://github.com/SyedOmarNooredu/Engine-sound-simulator---) (indirect because I forgot about forking before modifying it)
I have credited you in the Readme.
Are you OK with this?

**Comment by jgardner8** [comment]
Yeah, no worries mate. I'll check it out soon, sounds like you've done some cool stuff with it!
